author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 推送方式：0：邮件推送；1：qmsg推送(https://qmsg.zendee.cn/)
#2：pushplus微信推送(http://pushplus.hxtrip.com/)
sendType: 2
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''

#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第二个用户配置
  # 以下配置为信息收集
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        type: 0
        # 学校名称
        schoolName: '宜宾学院'
        # 账号
        username: ''
        # 密码
        password: ''
        # 定位位置信息
        address: '中国四川省宜宾市翠屏区大学路'
        #0 邮箱 1 QQ号 2 Pushplus token
        sendKey: ''
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 104.688848
        #经纬度信息
        lat: 28.824706
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
            - form:
                  title: 今日具体所在地
                  value: 四川省/宜宾市/翠屏区/大学路三段5号宜宾学院临港校区
            - form:
                  title: 是否在校
                  value: 是
            - form:
                  title: 上午体温
                  value: '36.3'
            - form:
                  title: 下午体温
                  value: '36.4'
            - form:
                  title: 晚上体温
                  value: '36.3'
            - form:
                  title: 身体状况
                  value: 身体健康
            - form:
                  title: 是否今日返校？
                  value: 否
